# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainQt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1395, 907)
        MainWindow.setMinimumSize(QtCore.QSize(560, 560))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 120, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 220, 81, 20))
        self.label_2.setObjectName("label_2")
        self.qt_attachment = QtWidgets.QPushButton(self.centralwidget)
        self.qt_attachment.setGeometry(QtCore.QRect(300, 790, 117, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qt_attachment.setFont(font)
        self.qt_attachment.setObjectName("qt_attachment")
        self.qt_send = QtWidgets.QPushButton(self.centralwidget)
        self.qt_send.setGeometry(QtCore.QRect(1200, 50, 117, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.qt_send.setFont(font)
        self.qt_send.setObjectName("qt_send")
        self.qt_email = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qt_email.setGeometry(QtCore.QRect(490, 110, 571, 71))
        self.qt_email.setMinimumSize(QtCore.QSize(311, 71))
        self.qt_email.setBackgroundVisible(False)
        self.qt_email.setCenterOnScroll(True)
        self.qt_email.setObjectName("qt_email")
        self.qt_subject = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qt_subject.setGeometry(QtCore.QRect(490, 200, 571, 71))
        self.qt_subject.setMinimumSize(QtCore.QSize(311, 0))
        self.qt_subject.setBackgroundVisible(False)
        self.qt_subject.setCenterOnScroll(True)
        self.qt_subject.setObjectName("qt_subject")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(470, 750, 611, 121))
        self.listView.setDragEnabled(True)
        self.listView.setDragDropOverwriteMode(True)
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 700, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 750, 271, 41))
        self.label_4.setObjectName("label_4")
        self.qt_Message = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qt_Message.setGeometry(QtCore.QRect(490, 280, 571, 331))
        self.qt_Message.setCenterOnScroll(True)
        self.qt_Message.setObjectName("qt_Message")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 380, 90, 23))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1395, 28))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionselect_File = QtWidgets.QAction(MainWindow)
        self.actionselect_File.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionselect_File.setObjectName("actionselect_File")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuMain.addAction(self.actionselect_File)
        self.menuMain.addAction(self.actionexit)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Email"))
        self.label_2.setText(_translate("MainWindow", "Subject"))
        self.qt_attachment.setText(_translate("MainWindow", "Attachment"))
        self.qt_send.setText(_translate("MainWindow", "Send"))
        self.qt_email.setToolTip(_translate("MainWindow", "<html><head/><body><p>Email</p></body></html>"))
        self.qt_subject.setToolTip(_translate("MainWindow", "<html><head/><body><p>Subject</p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "File Selected"))
        self.label_4.setText(_translate("MainWindow", "1.Prajal.Mp3"))
        self.label_5.setText(_translate("MainWindow", "Message"))
        self.menuMain.setTitle(_translate("MainWindow", "File"))
        self.actionselect_File.setText(_translate("MainWindow", "SecretKey"))
        self.actionselect_File.setStatusTip(_translate("MainWindow", "client secret Key"))
        self.actionselect_File.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionexit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
